pipeline {
    agent any

    tools {
        dockerTool 'docker'
    }

    environment {
        AWS_DEFAULT_REGION = 'eu-west-3'
        ECR_REGISTRY = '692701344220.dkr.ecr.eu-west-3.amazonaws.com'
        ECR_REPO     = 'cbz'
        APP1_TAG = "app1-${BUILD_NUMBER}"
        APP2_TAG = "app2-${BUILD_NUMBER}"
        CLUSTER_NAME = 'my-cluster'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/vishHzZ/sutomatic_rollback.git'
            }
        }

        stage('Install kubectl') {
            steps {
                sh '''
                if ! command -v kubectl >/dev/null; then
                  curl -LO https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
                  chmod +x kubectl
                  sudo mv kubectl /usr/local/bin/
                fi
                '''
            }
        }

        stage('AWS & ECR Login') {
            steps {
                withCredentials([
                    string(credentialsId: 'aws-id', keyVariable: 'AWS_ACCESS_KEY_ID'),
                    string(credentialsId: 'aws-key', keyVariable: 'AWS_SECRET_ACCESS_KEY')
                ]) {
                    sh '''
                    export AWS_ACCESS_KEY_ID
                    export AWS_SECRET_ACCESS_KEY
                    aws ecr get-login-password --region $AWS_DEFAULT_REGION |
                    docker login --username AWS --password-stdin $ECR_REGISTRY
                    '''
                }
            }
        }

        stage('Build & Push App1') {
            steps {
                sh '''
                docker build -t $ECR_REPO:$APP1_TAG .
                docker tag $ECR_REPO:$APP1_TAG $ECR_REGISTRY/$ECR_REPO:$APP1_TAG
                docker push $ECR_REGISTRY/$ECR_REPO:$APP1_TAG
                '''
            }
        }

        stage('Build & Push App2') {
            steps {
                dir('app2') {
                    sh '''
                    docker build -t $ECR_REPO:$APP2_TAG .
                    docker tag $ECR_REPO:$APP2_TAG $ECR_REGISTRY/$ECR_REPO:$APP2_TAG
                    docker push $ECR_REGISTRY/$ECR_REPO:$APP2_TAG
                    '''
                }
            }
        }

        stage('Connect to EKS') {
            steps {
                sh '''
                aws eks update-kubeconfig \
                  --name $CLUSTER_NAME \
                  --region $AWS_DEFAULT_REGION
                '''
            }
        }

        stage('Apply Kubernetes YAMLs') {
            steps {
                sh '''
                kubectl apply -f deployment.yaml
                kubectl apply -f service-app1.yaml
                kubectl apply -f app2/deployment-app2.yaml
                kubectl apply -f app2/service-app2.yaml
                '''
            }
        }

        stage('Deploy App1') {
            steps {
                script {
                    try {
                        sh "kubectl set image deployment/my-deployment my-container=$ECR_REGISTRY/$ECR_REPO:$APP1_TAG"
                        sh "kubectl rollout status deployment/my-deployment --timeout=180s"
                    } catch (e) {
                        sh "kubectl rollout undo deployment/my-deployment"
                        error "App1 rollback done"
                    }
                }
            }
        }

        stage('Deploy App2') {
            steps {
                script {
                    try {
                        sh "kubectl set image deployment/my-deployment-app2 my-container=$ECR_REGISTRY/$ECR_REPO:$APP2_TAG"
                        sh "kubectl rollout status deployment/my-deployment-app2 --timeout=180s"
                    } catch (e) {
                        sh "kubectl rollout undo deployment/my-deployment-app2"
                        error "App2 rollback done"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "🎉 BOTH APPS DEPLOYED WITH ZERO DOWNTIME"
        }
        failure {
            echo "❌ DEPLOYMENT FAILED – ROLLBACK EXECUTED"
        }
        always {
            sh 'docker system prune -f || true'
        }
    }
}
